import os
gettext = lambda s: s
DATA_DIR = os.path.dirname(os.path.dirname(__file__))
"""
Django settings for alarcogol project.

Generated by 'django-admin startproject' using Django 1.8.18.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-r3-e66fbpub4sv#ihd)%kgj5$e^c$u0w01iwapz07bouk@85x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition





ROOT_URLCONF = 'alarcogol.urls'



WSGI_APPLICATION = 'alarcogol.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases




# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(DATA_DIR, 'media')
STATIC_ROOT = os.path.join(DATA_DIR, 'static')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'alarcogol', 'static'),
)
SITE_ID = 1


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'alarcogol', 'templates'),],
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
    'django.contrib.messages.context_processors.messages',
    'django.template.context_processors.i18n',
    'django.template.context_processors.debug',
    'django.template.context_processors.request',
    'django.template.context_processors.media',
    'django.template.context_processors.csrf',
    'django.template.context_processors.tz',
    'sekizai.context_processors.sekizai',
    'django.template.context_processors.static',
    'cms.context_processors.cms_settings'
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
    'django.template.loaders.eggs.Loader'
            ],
        },
    },
]


MIDDLEWARE_CLASSES = (
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
    'cms.middleware.utils.ApphookReloadMiddleware'
)

INSTALLED_APPS = (
    'djangocms_admin_style',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'cms',
    'menus',
    'sekizai',
    'treebeard',
    'djangocms_text_ckeditor',
    'djangocms_column',
    'djangocms_link',
    'cmsplugin_filer_file',
    'cmsplugin_filer_folder',
    'cmsplugin_filer_image',
    'cmsplugin_filer_utils',
    'djangocms_snippet',
    'djangocms_googlemap',
    'djangocms_video',

    'aldryn_style',
    'easy_thumbnails',
    'mptt',
    'filer',
    'aldryn_bootstrap3',
    ## Instagram Conector
    'connected_accounts',
    'connected_accounts.providers',
    'djangocms_instagram',

    ##'cmsplugin_carousel',
    'alarcogol'
)

LANGUAGES = (
    ## Customize this
    ('es', gettext('es')),
)

CMS_LANGUAGES = {
    ## Customize this
    'default': {
        'public': True,
        'hide_untranslated': False,
        'redirect_on_fallback': True,
    },
    1: [
        {
            'public': True,
            'code': 'es',
            'hide_untranslated': False,
            'name': gettext('es'),
            'redirect_on_fallback': True,
        },
    ],
}

CMS_TEMPLATES = (
    ## Customize this
    ('fullwidth.html', 'Fullwidth'),
    ('home.html', 'Home'),
)

CMS_PERMISSION = True

CMS_PLACEHOLDER_CONF = {}

DATABASES = {
    'default': {
        'CONN_MAX_AGE': 0,
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'HOST': 'ec2-23-21-227-73.compute-1.amazonaws.com', #os.environ.get('DATABASE_HOST', ''),
        'NAME': 'd7dne8e2vo9ts7', #os.environ.get('DATABASE_NAME', ''),
        'PASSWORD': 'e0c53ed29d0e37209919801640157ef338089044a0270bda04113b8ceb5c05b4', #os.environ.get('DATABASE_PASS', ''),
        'PORT': '5432', #os.environ.get('DATABASE_PORT', ''),
        'USER': 'uelooavenygpgo' #os.environ.get('DATABASE_USER', '')
    }
}

MIGRATION_MODULES = {
    
}

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)

CKEDITOR_SETTINGS = {
    'stylesSet':[
        {
            'name': 'Page Header H1',
            'element': 'h1',
            'attributes':{
                'class': 'page-header',
            }
        },
        {
            'name': 'Page Header H2',
            'element': 'h2',
            'attributes':{
                'class': 'page-header',
            }
        },
        {
            'name': 'Page Header H3',
            'element': 'h3',
            'attributes':{
                'class': 'page-header',
            }
        },
        {
            'name': 'Code',
            'element': 'code',
        },
        {
            'name': 'Code Block',
            'element': 'pre',
            'attributes':{
                'class': 'code',
            }
        },
    ],
}

CONNECTED_ACCOUNTS_INSTAGRAM_CONSUMER_KEY = '66e6f1d3f96046f581ba76eef7eb97d4' #os.environ.get('INSTAGRAM_KEY', '')
CONNECTED_ACCOUNTS_INSTAGRAM_CONSUMER_SECRET = '5e654d37e4b5433cbfd93996238a90d5' #os.environ.get('INSTAGRAM_SECRET', '')
DJANGOCMS_INSTAGRAM_PLUGIN_MODULE = ('Generic')
DJANGOCMS_INSTAGRAM_PLUGIN_NAME = ('Instagram')
DJANGOCMS_INSTAGRAM_PAGE_ONLY = False
DJANGOCMS_INSTAGRAM_PARENT_CLASSES = None
DJANGOCMS_INSTAGRAM_REQUIRE_PARENT = False
DJANGOCMS_INSTAGRAM_TEXT_ENABLED = False
DJANGOCMS_INSTAGRAM_DEFAULT_TEMPLATE = 'instagram.html'

DJANGOCMS_INSTAGRAM_TEMPLATES = (
    ('djangocms_instagram/default.html', ('Default')),
    ('instagram.html', ('Cuuadricula')),
)